"""add class template

Revision ID: 1b53bf36b05d
Revises: 5c9b9640e6e7
Create Date: 2025-05-26 20:19:56.970174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b53bf36b05d'
down_revision: Union[str, None] = '5c9b9640e6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_levels', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('letters', postgresql.ARRAY(sa.String(length=1)), nullable=False),
    sa.Column('specializations', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_templates_id'), 'class_templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_class_templates_id'), table_name='class_templates')
    op.drop_table('class_templates')
    # ### end Alembic commands ###