"""implement column description in subject model

Revision ID: 21669747002b
Revises: 82ed44f6067c
Create Date: 2025-05-27 18:02:47.372530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21669747002b'
down_revision: Union[str, None] = '82ed44f6067c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('description', sa.String(), nullable=True))
    op.add_column('subjects', sa.Column('is_active', sa.Boolean(), default=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'description')
    op.drop_column('subjects', 'is_active')
    # ### end Alembic commands ###