"""add is sent for invites

Revision ID: 721eb1495115
Revises: db752ee68faa
Create Date: 2025-05-22 00:12:11.683732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '721eb1495115'
down_revision: Union[str, None] = 'db752ee68faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_invites', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('user_invites', sa.Column('token', sa.String(), nullable=False))
    op.add_column('user_invites', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.add_column('user_invites', sa.Column('is_sent', sa.Boolean(), nullable=True))
    op.drop_column('user_invites', 'invite_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_invites', sa.Column('invite_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user_invites', 'is_sent')
    op.drop_column('user_invites', 'expires_at')
    op.drop_column('user_invites', 'token')
    op.drop_column('user_invites', 'full_name')
    # ### end Alembic commands ###