"""add nullable for class transfer history

Revision ID: 82ed44f6067c
Revises: 1b53bf36b05d
Create Date: 2025-05-26 21:29:01.369902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82ed44f6067c'
down_revision: Union[str, None] = '1b53bf36b05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_class_history', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_class_history', 'class_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###